/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSMsgIdentificationNumber_H_
#define	_FANSMsgIdentificationNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSMsgIdentificationNumber */
typedef long	 FANSMsgIdentificationNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSMsgIdentificationNumber;
asn_struct_free_f FANSMsgIdentificationNumber_free;
asn_struct_print_f FANSMsgIdentificationNumber_print;
asn_constr_check_f FANSMsgIdentificationNumber_constraint;
ber_type_decoder_f FANSMsgIdentificationNumber_decode_ber;
der_type_encoder_f FANSMsgIdentificationNumber_encode_der;
xer_type_decoder_f FANSMsgIdentificationNumber_decode_xer;
xer_type_encoder_f FANSMsgIdentificationNumber_encode_xer;
per_type_decoder_f FANSMsgIdentificationNumber_decode_uper;
per_type_encoder_f FANSMsgIdentificationNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSMsgIdentificationNumber_H_ */
#include "asn_internal.h"
