/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSFixNextPlusOne_H_
#define	_FANSFixNextPlusOne_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSFixNextPlusOne */
typedef FANSPosition_t	 FANSFixNextPlusOne_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSFixNextPlusOne;
asn_struct_free_f FANSFixNextPlusOne_free;
asn_struct_print_f FANSFixNextPlusOne_print;
asn_constr_check_f FANSFixNextPlusOne_constraint;
ber_type_decoder_f FANSFixNextPlusOne_decode_ber;
der_type_encoder_f FANSFixNextPlusOne_encode_der;
xer_type_decoder_f FANSFixNextPlusOne_decode_xer;
xer_type_encoder_f FANSFixNextPlusOne_encode_xer;
per_type_decoder_f FANSFixNextPlusOne_decode_uper;
per_type_encoder_f FANSFixNextPlusOne_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSFixNextPlusOne_H_ */
#include "asn_internal.h"
