/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSFixName_H_
#define	_FANSFixName_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IA5String.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSFixName */
typedef IA5String_t	 FANSFixName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSFixName;
asn_struct_free_f FANSFixName_free;
asn_struct_print_f FANSFixName_print;
asn_constr_check_f FANSFixName_constraint;
ber_type_decoder_f FANSFixName_decode_ber;
der_type_encoder_f FANSFixName_encode_der;
xer_type_decoder_f FANSFixName_decode_xer;
xer_type_encoder_f FANSFixName_encode_xer;
per_type_decoder_f FANSFixName_decode_uper;
per_type_encoder_f FANSFixName_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSFixName_H_ */
#include "asn_internal.h"
