/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSAltitudeQFE_H_
#define	_FANSAltitudeQFE_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAltitudeQFE */
typedef long	 FANSAltitudeQFE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSAltitudeQFE;
asn_struct_free_f FANSAltitudeQFE_free;
asn_struct_print_f FANSAltitudeQFE_print;
asn_constr_check_f FANSAltitudeQFE_constraint;
ber_type_decoder_f FANSAltitudeQFE_decode_ber;
der_type_encoder_f FANSAltitudeQFE_encode_der;
xer_type_decoder_f FANSAltitudeQFE_decode_xer;
xer_type_encoder_f FANSAltitudeQFE_encode_xer;
per_type_decoder_f FANSAltitudeQFE_decode_uper;
per_type_encoder_f FANSAltitudeQFE_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAltitudeQFE_H_ */
#include "asn_internal.h"
