/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTimeEtaAtFixNext_H_
#define	_FANSTimeEtaAtFixNext_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSTimeEtaAtFixNext */
typedef FANSTime_t	 FANSTimeEtaAtFixNext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimeEtaAtFixNext;
asn_struct_free_f FANSTimeEtaAtFixNext_free;
asn_struct_print_f FANSTimeEtaAtFixNext_print;
asn_constr_check_f FANSTimeEtaAtFixNext_constraint;
ber_type_decoder_f FANSTimeEtaAtFixNext_decode_ber;
der_type_encoder_f FANSTimeEtaAtFixNext_encode_der;
xer_type_decoder_f FANSTimeEtaAtFixNext_decode_xer;
xer_type_encoder_f FANSTimeEtaAtFixNext_encode_xer;
per_type_decoder_f FANSTimeEtaAtFixNext_decode_uper;
per_type_encoder_f FANSTimeEtaAtFixNext_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTimeEtaAtFixNext_H_ */
#include "asn_internal.h"
