/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSProcedureArrival_H_
#define	_FANSProcedureArrival_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSProcedureName.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSProcedureArrival */
typedef FANSProcedureName_t	 FANSProcedureArrival_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSProcedureArrival;
asn_struct_free_f FANSProcedureArrival_free;
asn_struct_print_f FANSProcedureArrival_print;
asn_constr_check_f FANSProcedureArrival_constraint;
ber_type_decoder_f FANSProcedureArrival_decode_ber;
der_type_encoder_f FANSProcedureArrival_encode_der;
xer_type_decoder_f FANSProcedureArrival_decode_xer;
xer_type_encoder_f FANSProcedureArrival_encode_xer;
per_type_decoder_f FANSProcedureArrival_decode_uper;
per_type_encoder_f FANSProcedureArrival_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSProcedureArrival_H_ */
#include "asn_internal.h"
