/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "FANSTrackDetail.h"

static asn_TYPE_member_t asn_MBR_FANSTrackDetail_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTrackDetail, trackName),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_FANSTrackName,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"trackName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTrackDetail, latitudeLongitude_seqOf),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FANSLatitudeLongitudeSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"latitudeLongitude-seqOf"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSTrackDetail_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSTrackDetail_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* latitudeLongitude-seqOf */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 } /* trackName */
};
static asn_SEQUENCE_specifics_t asn_SPC_FANSTrackDetail_specs_1 = {
	sizeof(struct FANSTrackDetail),
	offsetof(struct FANSTrackDetail, _asn_ctx),
	asn_MAP_FANSTrackDetail_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FANSTrackDetail = {
	"FANSTrackDetail",
	"FANSTrackDetail",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_FANSTrackDetail_tags_1,
	sizeof(asn_DEF_FANSTrackDetail_tags_1)
		/sizeof(asn_DEF_FANSTrackDetail_tags_1[0]), /* 1 */
	asn_DEF_FANSTrackDetail_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSTrackDetail_tags_1)
		/sizeof(asn_DEF_FANSTrackDetail_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_FANSTrackDetail_1,
	2,	/* Elements count */
	&asn_SPC_FANSTrackDetail_specs_1	/* Additional specs */
};

