/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSLatitude_H_
#define	_FANSLatitude_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSLatitudeDegrees.h"
#include "FANSMinutesLatLon.h"
#include "FANSLatitudeDirection.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSLatitude */
typedef struct FANSLatitude {
	FANSLatitudeDegrees_t	 latitudeDegrees;
	FANSMinutesLatLon_t	*minutesLatLon	/* OPTIONAL */;
	FANSLatitudeDirection_t	 latitudeDirection;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSLatitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSLatitude;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSLatitude_H_ */
#include "asn_internal.h"
