/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSPositionCurrent_H_
#define	_FANSPositionCurrent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSPositionCurrent */
typedef FANSPosition_t	 FANSPositionCurrent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSPositionCurrent;
asn_struct_free_f FANSPositionCurrent_free;
asn_struct_print_f FANSPositionCurrent_print;
asn_constr_check_f FANSPositionCurrent_constraint;
ber_type_decoder_f FANSPositionCurrent_decode_ber;
der_type_encoder_f FANSPositionCurrent_encode_der;
xer_type_decoder_f FANSPositionCurrent_decode_xer;
xer_type_encoder_f FANSPositionCurrent_encode_xer;
per_type_decoder_f FANSPositionCurrent_decode_uper;
per_type_encoder_f FANSPositionCurrent_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSPositionCurrent_H_ */
#include "asn_internal.h"
