/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSWinds_H_
#define	_FANSWinds_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSWindDirection.h"
#include "FANSWindSpeed.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSWinds */
typedef struct FANSWinds {
	FANSWindDirection_t	 windDirection;
	FANSWindSpeed_t	 windSpeed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSWinds_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSWinds;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSWinds_H_ */
#include "asn_internal.h"
