/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSPlaceBearingDistance_H_
#define	_FANSPlaceBearingDistance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSFixName.h"
#include "FANSDegrees.h"
#include "FANSDistance.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSLatitudeLongitude;

/* FANSPlaceBearingDistance */
typedef struct FANSPlaceBearingDistance {
	FANSFixName_t	 fixName;
	struct FANSLatitudeLongitude	*latitudeLongitude	/* OPTIONAL */;
	FANSDegrees_t	 degrees;
	FANSDistance_t	 distance;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSPlaceBearingDistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSPlaceBearingDistance;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSLatitudeLongitude.h"

#endif	/* _FANSPlaceBearingDistance_H_ */
#include "asn_internal.h"
