/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSHoldatwaypointSpeedLow_H_
#define	_FANSHoldatwaypointSpeedLow_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSSpeed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSHoldatwaypointSpeedLow */
typedef FANSSpeed_t	 FANSHoldatwaypointSpeedLow_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSHoldatwaypointSpeedLow;
asn_struct_free_f FANSHoldatwaypointSpeedLow_free;
asn_struct_print_f FANSHoldatwaypointSpeedLow_print;
asn_constr_check_f FANSHoldatwaypointSpeedLow_constraint;
ber_type_decoder_f FANSHoldatwaypointSpeedLow_decode_ber;
der_type_encoder_f FANSHoldatwaypointSpeedLow_encode_der;
xer_type_decoder_f FANSHoldatwaypointSpeedLow_decode_xer;
xer_type_encoder_f FANSHoldatwaypointSpeedLow_encode_xer;
per_type_decoder_f FANSHoldatwaypointSpeedLow_decode_uper;
per_type_encoder_f FANSHoldatwaypointSpeedLow_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSHoldatwaypointSpeedLow_H_ */
#include "asn_internal.h"
