/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSSpeedMach_H_
#define	_FANSSpeedMach_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSSpeedMach */
typedef long	 FANSSpeedMach_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSSpeedMach;
asn_struct_free_f FANSSpeedMach_free;
asn_struct_print_f FANSSpeedMach_print;
asn_constr_check_f FANSSpeedMach_constraint;
ber_type_decoder_f FANSSpeedMach_decode_ber;
der_type_encoder_f FANSSpeedMach_encode_der;
xer_type_decoder_f FANSSpeedMach_decode_xer;
xer_type_encoder_f FANSSpeedMach_encode_xer;
per_type_decoder_f FANSSpeedMach_decode_uper;
per_type_encoder_f FANSSpeedMach_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSSpeedMach_H_ */
#include "asn_internal.h"
