/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSCOMNAVEquipmentStatusSequence_H_
#define	_FANSCOMNAVEquipmentStatusSequence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSCOMNAVEquipmentStatus.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSCOMNAVEquipmentStatusSequence */
typedef struct FANSCOMNAVEquipmentStatusSequence {
	A_SEQUENCE_OF(FANSCOMNAVEquipmentStatus_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSCOMNAVEquipmentStatusSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSCOMNAVEquipmentStatusSequence;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSCOMNAVEquipmentStatusSequence_H_ */
#include "asn_internal.h"
