/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTimeAtPositionCurrent_H_
#define	_FANSTimeAtPositionCurrent_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSTime.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSTimeAtPositionCurrent */
typedef FANSTime_t	 FANSTimeAtPositionCurrent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimeAtPositionCurrent;
asn_struct_free_f FANSTimeAtPositionCurrent_free;
asn_struct_print_f FANSTimeAtPositionCurrent_print;
asn_constr_check_f FANSTimeAtPositionCurrent_constraint;
ber_type_decoder_f FANSTimeAtPositionCurrent_decode_ber;
der_type_encoder_f FANSTimeAtPositionCurrent_encode_der;
xer_type_decoder_f FANSTimeAtPositionCurrent_decode_xer;
xer_type_encoder_f FANSTimeAtPositionCurrent_encode_xer;
per_type_decoder_f FANSTimeAtPositionCurrent_decode_uper;
per_type_encoder_f FANSTimeAtPositionCurrent_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTimeAtPositionCurrent_H_ */
#include "asn_internal.h"
