/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSAltitudePosition_H_
#define	_FANSAltitudePosition_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSAltitude.h"
#include "FANSPosition.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAltitudePosition */
typedef struct FANSAltitudePosition {
	FANSAltitude_t	 altitude;
	FANSPosition_t	 position;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSAltitudePosition_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSAltitudePosition;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAltitudePosition_H_ */
#include "asn_internal.h"
