/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSReportingPoints_H_
#define	_FANSReportingPoints_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSLatLonReportingPoints.h"
#include "FANSDegreeIncrement.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSReportingPoints */
typedef struct FANSReportingPoints {
	FANSLatLonReportingPoints_t	 latLonReportingPoints;
	FANSDegreeIncrement_t	*degreeIncrement	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSReportingPoints_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSReportingPoints;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSReportingPoints_H_ */
#include "asn_internal.h"
