/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSIcing_H_
#define	_FANSIcing_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSIcing {
	FANSIcing_trace	= 0,
	FANSIcing_light	= 1,
	FANSIcing_moderate	= 2,
	FANSIcing_severe	= 3
} e_FANSIcing;

/* FANSIcing */
typedef long	 FANSIcing_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSIcing;
asn_struct_free_f FANSIcing_free;
asn_struct_print_f FANSIcing_print;
asn_constr_check_f FANSIcing_constraint;
ber_type_decoder_f FANSIcing_decode_ber;
der_type_encoder_f FANSIcing_encode_der;
xer_type_decoder_f FANSIcing_decode_xer;
xer_type_encoder_f FANSIcing_encode_xer;
per_type_decoder_f FANSIcing_decode_uper;
per_type_encoder_f FANSIcing_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSIcing_H_ */
#include "asn_internal.h"
