/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSPositionProcedureName_H_
#define	_FANSPositionProcedureName_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"
#include "FANSProcedureName.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSPositionProcedureName */
typedef struct FANSPositionProcedureName {
	FANSPosition_t	 position;
	FANSProcedureName_t	 procedureName;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSPositionProcedureName_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSPositionProcedureName;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSPositionProcedureName_H_ */
#include "asn_internal.h"
