/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSDistanceOffsetNm_H_
#define	_FANSDistanceOffsetNm_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSDistanceOffsetNm */
typedef long	 FANSDistanceOffsetNm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSDistanceOffsetNm;
asn_struct_free_f FANSDistanceOffsetNm_free;
asn_struct_print_f FANSDistanceOffsetNm_print;
asn_constr_check_f FANSDistanceOffsetNm_constraint;
ber_type_decoder_f FANSDistanceOffsetNm_decode_ber;
der_type_encoder_f FANSDistanceOffsetNm_encode_der;
xer_type_decoder_f FANSDistanceOffsetNm_decode_xer;
xer_type_encoder_f FANSDistanceOffsetNm_encode_xer;
per_type_decoder_f FANSDistanceOffsetNm_decode_uper;
per_type_encoder_f FANSDistanceOffsetNm_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSDistanceOffsetNm_H_ */
#include "asn_internal.h"
