/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSWaypointSpeedAltitude_H_
#define	_FANSWaypointSpeedAltitude_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSSpeed;
struct FANSATWAltitudeSequence;

/* FANSWaypointSpeedAltitude */
typedef struct FANSWaypointSpeedAltitude {
	FANSPosition_t	 position;
	struct FANSSpeed	*speed	/* OPTIONAL */;
	struct FANSATWAltitudeSequence	*aTWaltitudesequence	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSWaypointSpeedAltitude_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSWaypointSpeedAltitude;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSSpeed.h"
#include "FANSATWAltitudeSequence.h"

#endif	/* _FANSWaypointSpeedAltitude_H_ */
#include "asn_internal.h"
