/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSSSREquipmentAvailable_H_
#define	_FANSSSREquipmentAvailable_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSSSREquipmentAvailable {
	FANSSSREquipmentAvailable_nnil	= 0,
	FANSSSREquipmentAvailable_atransponderModeA	= 1,
	FANSSSREquipmentAvailable_ctransponderModeAandC	= 2,
	FANSSSREquipmentAvailable_xtransponderModeS	= 3,
	FANSSSREquipmentAvailable_ptransponderModeSPA	= 4,
	FANSSSREquipmentAvailable_itransponderModeSID	= 5,
	FANSSSREquipmentAvailable_stransponderModeSPAID	= 6
} e_FANSSSREquipmentAvailable;

/* FANSSSREquipmentAvailable */
typedef long	 FANSSSREquipmentAvailable_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSSSREquipmentAvailable;
asn_struct_free_f FANSSSREquipmentAvailable_free;
asn_struct_print_f FANSSSREquipmentAvailable_print;
asn_constr_check_f FANSSSREquipmentAvailable_constraint;
ber_type_decoder_f FANSSSREquipmentAvailable_decode_ber;
der_type_encoder_f FANSSSREquipmentAvailable_encode_der;
xer_type_decoder_f FANSSSREquipmentAvailable_decode_xer;
xer_type_encoder_f FANSSSREquipmentAvailable_encode_xer;
per_type_decoder_f FANSSSREquipmentAvailable_decode_uper;
per_type_encoder_f FANSSSREquipmentAvailable_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSSSREquipmentAvailable_H_ */
#include "asn_internal.h"
