/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSFixNext_H_
#define	_FANSFixNext_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSFixNext */
typedef FANSPosition_t	 FANSFixNext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSFixNext;
asn_struct_free_f FANSFixNext_free;
asn_struct_print_f FANSFixNext_print;
asn_constr_check_f FANSFixNext_constraint;
ber_type_decoder_f FANSFixNext_decode_ber;
der_type_encoder_f FANSFixNext_encode_der;
xer_type_decoder_f FANSFixNext_decode_xer;
xer_type_encoder_f FANSFixNext_encode_xer;
per_type_decoder_f FANSFixNext_decode_uper;
per_type_encoder_f FANSFixNext_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSFixNext_H_ */
#include "asn_internal.h"
