/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSATCDownlinkMsgElementIdSequence_H_
#define	_FANSATCDownlinkMsgElementIdSequence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSATCDownlinkMsgElementId;

/* FANSATCDownlinkMsgElementIdSequence */
typedef struct FANSATCDownlinkMsgElementIdSequence {
	A_SEQUENCE_OF(struct FANSATCDownlinkMsgElementId) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSATCDownlinkMsgElementIdSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSATCDownlinkMsgElementIdSequence;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSATCDownlinkMsgElementId.h"

#endif	/* _FANSATCDownlinkMsgElementIdSequence_H_ */
#include "asn_internal.h"
