/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSProcedureType_H_
#define	_FANSProcedureType_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSProcedureType {
	FANSProcedureType_arrival	= 0,
	FANSProcedureType_approach	= 1,
	FANSProcedureType_departure	= 2
} e_FANSProcedureType;

/* FANSProcedureType */
typedef long	 FANSProcedureType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSProcedureType;
asn_struct_free_f FANSProcedureType_free;
asn_struct_print_f FANSProcedureType_print;
asn_constr_check_f FANSProcedureType_constraint;
ber_type_decoder_f FANSProcedureType_decode_ber;
der_type_encoder_f FANSProcedureType_encode_der;
xer_type_decoder_f FANSProcedureType_decode_xer;
xer_type_encoder_f FANSProcedureType_encode_xer;
per_type_decoder_f FANSProcedureType_decode_uper;
per_type_encoder_f FANSProcedureType_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSProcedureType_H_ */
#include "asn_internal.h"
