/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSDegreesMagnetic_H_
#define	_FANSDegreesMagnetic_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSDegreesMagnetic */
typedef long	 FANSDegreesMagnetic_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSDegreesMagnetic;
asn_struct_free_f FANSDegreesMagnetic_free;
asn_struct_print_f FANSDegreesMagnetic_print;
asn_constr_check_f FANSDegreesMagnetic_constraint;
ber_type_decoder_f FANSDegreesMagnetic_decode_ber;
der_type_encoder_f FANSDegreesMagnetic_encode_der;
xer_type_decoder_f FANSDegreesMagnetic_decode_xer;
xer_type_encoder_f FANSDegreesMagnetic_encode_xer;
per_type_decoder_f FANSDegreesMagnetic_decode_uper;
per_type_encoder_f FANSDegreesMagnetic_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSDegreesMagnetic_H_ */
#include "asn_internal.h"
