/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSAltitudeFlightLevelMetric_H_
#define	_FANSAltitudeFlightLevelMetric_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAltitudeFlightLevelMetric */
typedef long	 FANSAltitudeFlightLevelMetric_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSAltitudeFlightLevelMetric;
asn_struct_free_f FANSAltitudeFlightLevelMetric_free;
asn_struct_print_f FANSAltitudeFlightLevelMetric_print;
asn_constr_check_f FANSAltitudeFlightLevelMetric_constraint;
ber_type_decoder_f FANSAltitudeFlightLevelMetric_decode_ber;
der_type_encoder_f FANSAltitudeFlightLevelMetric_encode_der;
xer_type_decoder_f FANSAltitudeFlightLevelMetric_decode_xer;
xer_type_encoder_f FANSAltitudeFlightLevelMetric_encode_xer;
per_type_decoder_f FANSAltitudeFlightLevelMetric_decode_uper;
per_type_encoder_f FANSAltitudeFlightLevelMetric_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAltitudeFlightLevelMetric_H_ */
#include "asn_internal.h"
