/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSSpeedSpeed_H_
#define	_FANSSpeedSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSSpeed;

/* FANSSpeedSpeed */
typedef struct FANSSpeedSpeed {
	A_SEQUENCE_OF(struct FANSSpeed) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSSpeedSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSSpeedSpeed;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSSpeed.h"

#endif	/* _FANSSpeedSpeed_H_ */
#include "asn_internal.h"
