/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSRTATime_H_
#define	_FANSRTATime_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSTime.h"
#include "FANSTimeTolerance.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSRTATime */
typedef struct FANSRTATime {
	FANSTime_t	 time;
	FANSTimeTolerance_t	 timeTolerance;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSRTATime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSRTATime;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSRTATime_H_ */
#include "asn_internal.h"
