/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSWindSpeed_H_
#define	_FANSWindSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSWindSpeedEnglish.h"
#include "FANSWindSpeedMetric.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSWindSpeed_PR {
	FANSWindSpeed_PR_NOTHING,	/* No components present */
	FANSWindSpeed_PR_windSpeedEnglish,
	FANSWindSpeed_PR_windSpeedMetric
} FANSWindSpeed_PR;

/* FANSWindSpeed */
typedef struct FANSWindSpeed {
	FANSWindSpeed_PR present;
	union FANSWindSpeed_u {
		FANSWindSpeedEnglish_t	 windSpeedEnglish;
		FANSWindSpeedMetric_t	 windSpeedMetric;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSWindSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSWindSpeed;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSWindSpeed_H_ */
#include "asn_internal.h"
