/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTemperatureF_H_
#define	_FANSTemperatureF_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSTemperatureF */
typedef long	 FANSTemperatureF_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTemperatureF;
asn_struct_free_f FANSTemperatureF_free;
asn_struct_print_f FANSTemperatureF_print;
asn_constr_check_f FANSTemperatureF_constraint;
ber_type_decoder_f FANSTemperatureF_decode_ber;
der_type_encoder_f FANSTemperatureF_encode_der;
xer_type_decoder_f FANSTemperatureF_decode_xer;
xer_type_encoder_f FANSTemperatureF_encode_xer;
per_type_decoder_f FANSTemperatureF_decode_uper;
per_type_encoder_f FANSTemperatureF_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTemperatureF_H_ */
#include "asn_internal.h"
