/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "FANSRouteInformationAdditional.h"

static asn_TYPE_member_t asn_MBR_FANSRouteInformationAdditional_1[] = {
	{ ATF_POINTER, 6, offsetof(struct FANSRouteInformationAdditional, aTWalongtrackwaypointsequence),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSATWAlongTrackWaypointSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"aTWalongtrackwaypointsequence"
		},
	{ ATF_POINTER, 5, offsetof(struct FANSRouteInformationAdditional, reportingPoints),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSReportingPoints,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportingPoints"
		},
	{ ATF_POINTER, 4, offsetof(struct FANSRouteInformationAdditional, interceptCourseFromSequence),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSInterceptCourseFromSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"interceptCourseFromSequence"
		},
	{ ATF_POINTER, 3, offsetof(struct FANSRouteInformationAdditional, holdAtWaypointSequence),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSHoldatwaypointSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"holdAtWaypointSequence"
		},
	{ ATF_POINTER, 2, offsetof(struct FANSRouteInformationAdditional, waypointSpeedAltitudeSequence),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSWaypointSpeedAltitudesequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"waypointSpeedAltitudeSequence"
		},
	{ ATF_POINTER, 1, offsetof(struct FANSRouteInformationAdditional, rTArequiredtimearrivalsequenc),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSRTARequiredTimeArrivalSequence,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rTArequiredtimearrivalsequenc"
		},
};
static const int asn_MAP_FANSRouteInformationAdditional_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_FANSRouteInformationAdditional_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSRouteInformationAdditional_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* aTWalongtrackwaypointsequence */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reportingPoints */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* interceptCourseFromSequence */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* holdAtWaypointSequence */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* waypointSpeedAltitudeSequence */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* rTArequiredtimearrivalsequenc */
};
static asn_SEQUENCE_specifics_t asn_SPC_FANSRouteInformationAdditional_specs_1 = {
	sizeof(struct FANSRouteInformationAdditional),
	offsetof(struct FANSRouteInformationAdditional, _asn_ctx),
	asn_MAP_FANSRouteInformationAdditional_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_FANSRouteInformationAdditional_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FANSRouteInformationAdditional = {
	"FANSRouteInformationAdditional",
	"FANSRouteInformationAdditional",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_FANSRouteInformationAdditional_tags_1,
	sizeof(asn_DEF_FANSRouteInformationAdditional_tags_1)
		/sizeof(asn_DEF_FANSRouteInformationAdditional_tags_1[0]), /* 1 */
	asn_DEF_FANSRouteInformationAdditional_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSRouteInformationAdditional_tags_1)
		/sizeof(asn_DEF_FANSRouteInformationAdditional_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_FANSRouteInformationAdditional_1,
	6,	/* Elements count */
	&asn_SPC_FANSRouteInformationAdditional_specs_1	/* Additional specs */
};

