/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSAltitudeGNSSFeet_H_
#define	_FANSAltitudeGNSSFeet_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAltitudeGNSSFeet */
typedef long	 FANSAltitudeGNSSFeet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSAltitudeGNSSFeet;
asn_struct_free_f FANSAltitudeGNSSFeet_free;
asn_struct_print_f FANSAltitudeGNSSFeet_print;
asn_constr_check_f FANSAltitudeGNSSFeet_constraint;
ber_type_decoder_f FANSAltitudeGNSSFeet_decode_ber;
der_type_encoder_f FANSAltitudeGNSSFeet_encode_der;
xer_type_decoder_f FANSAltitudeGNSSFeet_decode_xer;
xer_type_encoder_f FANSAltitudeGNSSFeet_encode_xer;
per_type_decoder_f FANSAltitudeGNSSFeet_decode_uper;
per_type_encoder_f FANSAltitudeGNSSFeet_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAltitudeGNSSFeet_H_ */
#include "asn_internal.h"
