/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSLatitudeLongitudeSequence_H_
#define	_FANSLatitudeLongitudeSequence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSLatitudeLongitude;

/* FANSLatitudeLongitudeSequence */
typedef struct FANSLatitudeLongitudeSequence {
	A_SEQUENCE_OF(struct FANSLatitudeLongitude) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSLatitudeLongitudeSequence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSLatitudeLongitudeSequence;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSLatitudeLongitude.h"

#endif	/* _FANSLatitudeLongitudeSequence_H_ */
#include "asn_internal.h"
