/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTimehours_H_
#define	_FANSTimehours_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSTimehours */
typedef long	 FANSTimehours_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimehours;
asn_struct_free_f FANSTimehours_free;
asn_struct_print_f FANSTimehours_print;
asn_constr_check_f FANSTimehours_constraint;
ber_type_decoder_f FANSTimehours_decode_ber;
der_type_encoder_f FANSTimehours_encode_der;
xer_type_decoder_f FANSTimehours_decode_xer;
xer_type_encoder_f FANSTimehours_encode_xer;
per_type_decoder_f FANSTimehours_decode_uper;
per_type_encoder_f FANSTimehours_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTimehours_H_ */
#include "asn_internal.h"
