/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTimeICAOunitnameFrequency_H_
#define	_FANSTimeICAOunitnameFrequency_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSTime.h"
#include "FANSICAOUnitName.h"
#include "FANSFrequency.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSTimeICAOunitnameFrequency */
typedef struct FANSTimeICAOunitnameFrequency {
	FANSTime_t	 time;
	FANSICAOUnitName_t	 iCAOUnitName;
	FANSFrequency_t	 frequency;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSTimeICAOunitnameFrequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimeICAOunitnameFrequency;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTimeICAOunitnameFrequency_H_ */
#include "asn_internal.h"
