/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSRunwayArrival_H_
#define	_FANSRunwayArrival_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSRunway.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSRunwayArrival */
typedef FANSRunway_t	 FANSRunwayArrival_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSRunwayArrival;
asn_struct_free_f FANSRunwayArrival_free;
asn_struct_print_f FANSRunwayArrival_print;
asn_constr_check_f FANSRunwayArrival_constraint;
ber_type_decoder_f FANSRunwayArrival_decode_ber;
der_type_encoder_f FANSRunwayArrival_encode_der;
xer_type_decoder_f FANSRunwayArrival_decode_xer;
xer_type_encoder_f FANSRunwayArrival_encode_xer;
per_type_decoder_f FANSRunwayArrival_decode_uper;
per_type_encoder_f FANSRunwayArrival_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSRunwayArrival_H_ */
#include "asn_internal.h"
