/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSProcedure_H_
#define	_FANSProcedure_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IA5String.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSProcedure */
typedef IA5String_t	 FANSProcedure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSProcedure;
asn_struct_free_f FANSProcedure_free;
asn_struct_print_f FANSProcedure_print;
asn_constr_check_f FANSProcedure_constraint;
ber_type_decoder_f FANSProcedure_decode_ber;
der_type_encoder_f FANSProcedure_encode_der;
xer_type_decoder_f FANSProcedure_decode_xer;
xer_type_encoder_f FANSProcedure_encode_xer;
per_type_decoder_f FANSProcedure_decode_uper;
per_type_encoder_f FANSProcedure_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSProcedure_H_ */
#include "asn_internal.h"
