/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTimeTolerance_H_
#define	_FANSTimeTolerance_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSTimeTolerance {
	FANSTimeTolerance_at	= 0,
	FANSTimeTolerance_atorafter	= 1,
	FANSTimeTolerance_atorbefore	= 2
} e_FANSTimeTolerance;

/* FANSTimeTolerance */
typedef long	 FANSTimeTolerance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimeTolerance;
asn_struct_free_f FANSTimeTolerance_free;
asn_struct_print_f FANSTimeTolerance_print;
asn_constr_check_f FANSTimeTolerance_constraint;
ber_type_decoder_f FANSTimeTolerance_decode_ber;
der_type_encoder_f FANSTimeTolerance_encode_der;
xer_type_decoder_f FANSTimeTolerance_decode_xer;
xer_type_encoder_f FANSTimeTolerance_encode_xer;
per_type_decoder_f FANSTimeTolerance_decode_uper;
per_type_encoder_f FANSTimeTolerance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTimeTolerance_H_ */
#include "asn_internal.h"
