/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSHoldatwaypointSpeedHigh_H_
#define	_FANSHoldatwaypointSpeedHigh_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSSpeed.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSHoldatwaypointSpeedHigh */
typedef FANSSpeed_t	 FANSHoldatwaypointSpeedHigh_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSHoldatwaypointSpeedHigh;
asn_struct_free_f FANSHoldatwaypointSpeedHigh_free;
asn_struct_print_f FANSHoldatwaypointSpeedHigh_print;
asn_constr_check_f FANSHoldatwaypointSpeedHigh_constraint;
ber_type_decoder_f FANSHoldatwaypointSpeedHigh_decode_ber;
der_type_encoder_f FANSHoldatwaypointSpeedHigh_encode_der;
xer_type_decoder_f FANSHoldatwaypointSpeedHigh_decode_xer;
xer_type_encoder_f FANSHoldatwaypointSpeedHigh_encode_xer;
per_type_decoder_f FANSHoldatwaypointSpeedHigh_decode_uper;
per_type_encoder_f FANSHoldatwaypointSpeedHigh_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSHoldatwaypointSpeedHigh_H_ */
#include "asn_internal.h"
