/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSRunway_H_
#define	_FANSRunway_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSRunwayDirection.h"
#include "FANSRunwayConfiguration.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSRunway */
typedef struct FANSRunway {
	FANSRunwayDirection_t	 runwayDirection;
	FANSRunwayConfiguration_t	 runwayConfiguration;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSRunway_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSRunway;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSRunway_H_ */
#include "asn_internal.h"
