/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSDistanceKm_H_
#define	_FANSDistanceKm_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSDistanceKm */
typedef long	 FANSDistanceKm_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSDistanceKm;
asn_struct_free_f FANSDistanceKm_free;
asn_struct_print_f FANSDistanceKm_print;
asn_constr_check_f FANSDistanceKm_constraint;
ber_type_decoder_f FANSDistanceKm_decode_ber;
der_type_encoder_f FANSDistanceKm_encode_der;
xer_type_decoder_f FANSDistanceKm_decode_xer;
xer_type_encoder_f FANSDistanceKm_encode_xer;
per_type_decoder_f FANSDistanceKm_decode_uper;
per_type_encoder_f FANSDistanceKm_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSDistanceKm_H_ */
#include "asn_internal.h"
