/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSPDCrevision_H_
#define	_FANSPDCrevision_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSPDCrevision */
typedef long	 FANSPDCrevision_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSPDCrevision;
asn_struct_free_f FANSPDCrevision_free;
asn_struct_print_f FANSPDCrevision_print;
asn_constr_check_f FANSPDCrevision_constraint;
ber_type_decoder_f FANSPDCrevision_decode_ber;
der_type_encoder_f FANSPDCrevision_encode_der;
xer_type_decoder_f FANSPDCrevision_decode_xer;
xer_type_encoder_f FANSPDCrevision_encode_xer;
per_type_decoder_f FANSPDCrevision_decode_uper;
per_type_encoder_f FANSPDCrevision_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSPDCrevision_H_ */
#include "asn_internal.h"
