/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSAircraftEquipmentCode_H_
#define	_FANSAircraftEquipmentCode_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSCOMNAVApproachEquipmentAvailable.h"
#include "FANSSSREquipmentAvailable.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FANSCOMNAVEquipmentStatusSequence;

/* FANSAircraftEquipmentCode */
typedef struct FANSAircraftEquipmentCode {
	FANSCOMNAVApproachEquipmentAvailable_t	 cOMNAVApproachEquipmentAvailable;
	struct FANSCOMNAVEquipmentStatusSequence	*comnavequipmentstatus_seqOf	/* OPTIONAL */;
	FANSSSREquipmentAvailable_t	 sSREquipmentAvailable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSAircraftEquipmentCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSAircraftEquipmentCode;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FANSCOMNAVEquipmentStatusSequence.h"

#endif	/* _FANSAircraftEquipmentCode_H_ */
#include "asn_internal.h"
