/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSICAOFacilityIdentification_H_
#define	_FANSICAOFacilityIdentification_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSICAOfacilityDesignation.h"
#include "FANSICAOFacilityName.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSICAOFacilityIdentification_PR {
	FANSICAOFacilityIdentification_PR_NOTHING,	/* No components present */
	FANSICAOFacilityIdentification_PR_iCAOfacilitydesignation,
	FANSICAOFacilityIdentification_PR_iCAOfacilityname
} FANSICAOFacilityIdentification_PR;

/* FANSICAOFacilityIdentification */
typedef struct FANSICAOFacilityIdentification {
	FANSICAOFacilityIdentification_PR present;
	union FANSICAOFacilityIdentification_u {
		FANSICAOfacilityDesignation_t	 iCAOfacilitydesignation;
		FANSICAOFacilityName_t	 iCAOfacilityname;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSICAOFacilityIdentification_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSICAOFacilityIdentification;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSICAOFacilityIdentification_H_ */
#include "asn_internal.h"
