/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSAirportDeparture_H_
#define	_FANSAirportDeparture_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSAirport.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSAirportDeparture */
typedef FANSAirport_t	 FANSAirportDeparture_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSAirportDeparture;
asn_struct_free_f FANSAirportDeparture_free;
asn_struct_print_f FANSAirportDeparture_print;
asn_constr_check_f FANSAirportDeparture_constraint;
ber_type_decoder_f FANSAirportDeparture_decode_ber;
der_type_encoder_f FANSAirportDeparture_encode_der;
xer_type_decoder_f FANSAirportDeparture_decode_xer;
xer_type_encoder_f FANSAirportDeparture_encode_xer;
per_type_decoder_f FANSAirportDeparture_decode_uper;
per_type_encoder_f FANSAirportDeparture_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSAirportDeparture_H_ */
#include "asn_internal.h"
