/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "FANSTimeDistanceToFromPosition.h"

static asn_TYPE_member_t asn_MBR_FANSTimeDistanceToFromPosition_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTimeDistanceToFromPosition, time),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"time"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTimeDistanceToFromPosition, distance),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_FANSDistance,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"distance"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTimeDistanceToFromPosition, toFrom),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_FANSToFrom,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"toFrom"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct FANSTimeDistanceToFromPosition, position),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_FANSPosition,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"position"
		},
};
static const ber_tlv_tag_t asn_DEF_FANSTimeDistanceToFromPosition_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSTimeDistanceToFromPosition_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* time */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* distance */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* toFrom */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* position */
};
static asn_SEQUENCE_specifics_t asn_SPC_FANSTimeDistanceToFromPosition_specs_1 = {
	sizeof(struct FANSTimeDistanceToFromPosition),
	offsetof(struct FANSTimeDistanceToFromPosition, _asn_ctx),
	asn_MAP_FANSTimeDistanceToFromPosition_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FANSTimeDistanceToFromPosition = {
	"FANSTimeDistanceToFromPosition",
	"FANSTimeDistanceToFromPosition",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_FANSTimeDistanceToFromPosition_tags_1,
	sizeof(asn_DEF_FANSTimeDistanceToFromPosition_tags_1)
		/sizeof(asn_DEF_FANSTimeDistanceToFromPosition_tags_1[0]), /* 1 */
	asn_DEF_FANSTimeDistanceToFromPosition_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSTimeDistanceToFromPosition_tags_1)
		/sizeof(asn_DEF_FANSTimeDistanceToFromPosition_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_FANSTimeDistanceToFromPosition_1,
	4,	/* Elements count */
	&asn_SPC_FANSTimeDistanceToFromPosition_specs_1	/* Additional specs */
};

