/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTimeSpeed_H_
#define	_FANSTimeSpeed_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSTime.h"
#include "FANSSpeed.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSTimeSpeed */
typedef struct FANSTimeSpeed {
	FANSTime_t	 time;
	FANSSpeed_t	 speed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSTimeSpeed_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimeSpeed;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTimeSpeed_H_ */
#include "asn_internal.h"
