/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "FANSTrueheading.h"

int
FANSTrueheading_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_FANSDegrees.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using FANSDegrees,
 * so here we adjust the DEF accordingly.
 */
static void
FANSTrueheading_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_FANSDegrees.free_struct;
	td->print_struct   = asn_DEF_FANSDegrees.print_struct;
	td->check_constraints = asn_DEF_FANSDegrees.check_constraints;
	td->ber_decoder    = asn_DEF_FANSDegrees.ber_decoder;
	td->der_encoder    = asn_DEF_FANSDegrees.der_encoder;
	td->xer_decoder    = asn_DEF_FANSDegrees.xer_decoder;
	td->xer_encoder    = asn_DEF_FANSDegrees.xer_encoder;
	td->uper_decoder   = asn_DEF_FANSDegrees.uper_decoder;
	td->uper_encoder   = asn_DEF_FANSDegrees.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_FANSDegrees.per_constraints;
	td->elements       = asn_DEF_FANSDegrees.elements;
	td->elements_count = asn_DEF_FANSDegrees.elements_count;
	td->specifics      = asn_DEF_FANSDegrees.specifics;
}

void
FANSTrueheading_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	FANSTrueheading_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
FANSTrueheading_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	FANSTrueheading_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
FANSTrueheading_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	FANSTrueheading_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
FANSTrueheading_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	FANSTrueheading_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
FANSTrueheading_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	FANSTrueheading_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
FANSTrueheading_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	FANSTrueheading_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_dec_rval_t
FANSTrueheading_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	FANSTrueheading_1_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
FANSTrueheading_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	FANSTrueheading_1_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_FANSTrueheading_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_descriptor_t asn_DEF_FANSTrueheading = {
	"FANSTrueheading",
	"FANSTrueheading",
	FANSTrueheading_free,
	FANSTrueheading_print,
	FANSTrueheading_constraint,
	FANSTrueheading_decode_ber,
	FANSTrueheading_encode_der,
	FANSTrueheading_decode_xer,
	FANSTrueheading_encode_xer,
	FANSTrueheading_decode_uper,
	FANSTrueheading_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	0	/* No specifics */
};

