/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSLatLonReportingPoints_H_
#define	_FANSLatLonReportingPoints_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSLatitudeReportingPoints.h"
#include "FANSLongitudeReportingPoints.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSLatLonReportingPoints_PR {
	FANSLatLonReportingPoints_PR_NOTHING,	/* No components present */
	FANSLatLonReportingPoints_PR_latitudeReportingPoints,
	FANSLatLonReportingPoints_PR_longitudeReportingPoints
} FANSLatLonReportingPoints_PR;

/* FANSLatLonReportingPoints */
typedef struct FANSLatLonReportingPoints {
	FANSLatLonReportingPoints_PR present;
	union FANSLatLonReportingPoints_u {
		FANSLatitudeReportingPoints_t	 latitudeReportingPoints;
		FANSLongitudeReportingPoints_t	 longitudeReportingPoints;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSLatLonReportingPoints_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSLatLonReportingPoints;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSLatLonReportingPoints_H_ */
#include "asn_internal.h"
