/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTimeDistanceOffsetDirection_H_
#define	_FANSTimeDistanceOffsetDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSTime.h"
#include "FANSDistanceOffset.h"
#include "FANSDirection.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSTimeDistanceOffsetDirection */
typedef struct FANSTimeDistanceOffsetDirection {
	FANSTime_t	 time;
	FANSDistanceOffset_t	 distanceOffset;
	FANSDirection_t	 direction;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSTimeDistanceOffsetDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTimeDistanceOffsetDirection;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTimeDistanceOffsetDirection_H_ */
#include "asn_internal.h"
