/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#include "FANSPublishedIdentifier.h"

static asn_TYPE_member_t asn_MBR_FANSPublishedIdentifier_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct FANSPublishedIdentifier, fixName),
		(ASN_TAG_CLASS_UNIVERSAL | (22 << 2)),
		0,
		&asn_DEF_FANSFixName,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fixName"
		},
	{ ATF_POINTER, 1, offsetof(struct FANSPublishedIdentifier, latitudeLongitude),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FANSLatitudeLongitude,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"latitudeLongitude"
		},
};
static const int asn_MAP_FANSPublishedIdentifier_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_FANSPublishedIdentifier_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_FANSPublishedIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* latitudeLongitude */
    { (ASN_TAG_CLASS_UNIVERSAL | (22 << 2)), 0, 0, 0 } /* fixName */
};
static asn_SEQUENCE_specifics_t asn_SPC_FANSPublishedIdentifier_specs_1 = {
	sizeof(struct FANSPublishedIdentifier),
	offsetof(struct FANSPublishedIdentifier, _asn_ctx),
	asn_MAP_FANSPublishedIdentifier_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_FANSPublishedIdentifier_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_FANSPublishedIdentifier = {
	"FANSPublishedIdentifier",
	"FANSPublishedIdentifier",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_FANSPublishedIdentifier_tags_1,
	sizeof(asn_DEF_FANSPublishedIdentifier_tags_1)
		/sizeof(asn_DEF_FANSPublishedIdentifier_tags_1[0]), /* 1 */
	asn_DEF_FANSPublishedIdentifier_tags_1,	/* Same as above */
	sizeof(asn_DEF_FANSPublishedIdentifier_tags_1)
		/sizeof(asn_DEF_FANSPublishedIdentifier_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_FANSPublishedIdentifier_1,
	2,	/* Elements count */
	&asn_SPC_FANSPublishedIdentifier_specs_1	/* Additional specs */
};

