/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSSupplementaryInformation_H_
#define	_FANSSupplementaryInformation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSFreeText.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSSupplementaryInformation */
typedef FANSFreeText_t	 FANSSupplementaryInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSSupplementaryInformation;
asn_struct_free_f FANSSupplementaryInformation_free;
asn_struct_print_f FANSSupplementaryInformation_print;
asn_constr_check_f FANSSupplementaryInformation_constraint;
ber_type_decoder_f FANSSupplementaryInformation_decode_ber;
der_type_encoder_f FANSSupplementaryInformation_encode_der;
xer_type_decoder_f FANSSupplementaryInformation_decode_xer;
xer_type_encoder_f FANSSupplementaryInformation_encode_xer;
per_type_decoder_f FANSSupplementaryInformation_decode_uper;
per_type_encoder_f FANSSupplementaryInformation_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSSupplementaryInformation_H_ */
#include "asn_internal.h"
