/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSTurbulence_H_
#define	_FANSTurbulence_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FANSTurbulence {
	FANSTurbulence_light	= 0,
	FANSTurbulence_moderate	= 1,
	FANSTurbulence_severe	= 2
} e_FANSTurbulence;

/* FANSTurbulence */
typedef long	 FANSTurbulence_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSTurbulence;
asn_struct_free_f FANSTurbulence_free;
asn_struct_print_f FANSTurbulence_print;
asn_constr_check_f FANSTurbulence_constraint;
ber_type_decoder_f FANSTurbulence_decode_ber;
der_type_encoder_f FANSTurbulence_encode_der;
xer_type_decoder_f FANSTurbulence_decode_xer;
xer_type_encoder_f FANSTurbulence_encode_xer;
per_type_decoder_f FANSTurbulence_decode_uper;
per_type_encoder_f FANSTurbulence_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSTurbulence_H_ */
#include "asn_internal.h"
