/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSWindDirection_H_
#define	_FANSWindDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSWindDirection */
typedef long	 FANSWindDirection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSWindDirection;
asn_struct_free_f FANSWindDirection_free;
asn_struct_print_f FANSWindDirection_print;
asn_constr_check_f FANSWindDirection_constraint;
ber_type_decoder_f FANSWindDirection_decode_ber;
der_type_encoder_f FANSWindDirection_encode_der;
xer_type_decoder_f FANSWindDirection_decode_xer;
xer_type_encoder_f FANSWindDirection_encode_xer;
per_type_decoder_f FANSWindDirection_decode_uper;
per_type_encoder_f FANSWindDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSWindDirection_H_ */
#include "asn_internal.h"
