/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "FANSACTwoWayDataLinkCommunications"
 * 	found in "../../../libacars.asn1/fans-cpdlc.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -gen-PER`
 */

#ifndef	_FANSRTARequiredTimeArrival_H_
#define	_FANSRTARequiredTimeArrival_H_


#include "asn_application.h"

/* Including external dependencies */
#include "FANSPosition.h"
#include "FANSRTATime.h"
#include "FANSRTATolerance.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* FANSRTARequiredTimeArrival */
typedef struct FANSRTARequiredTimeArrival {
	FANSPosition_t	 position;
	FANSRTATime_t	 rTATime;
	FANSRTATolerance_t	*rTATolerance	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FANSRTARequiredTimeArrival_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FANSRTARequiredTimeArrival;

#ifdef __cplusplus
}
#endif

#endif	/* _FANSRTARequiredTimeArrival_H_ */
#include "asn_internal.h"
