{
    "RGB-221": {
        "expression": "ch2, ch2, ch1",
        "corrected": true
    },
    "RGB-221-EQU": {
        "expression": "ch2, ch2, ch1",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    },
    "RGB-621": {
        "expression": "ch6, ch2, ch1",
        "corrected": true
    },
    "RGB-621-EQU": {
        "expression": "ch6, ch2, ch1",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    },
    "RGB-197": {
        "expression": "ch1, ch9, ch7",
        "corrected": true
    },
    "RGB-197-EQU": {
        "expression": "ch1, ch9, ch7",
        "pre_equalize": true,
        "equalize": true,
        "corrected": true,
        "projected": true
    },
    "4-EQU": {
        "expression": "ch4",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    }
}