{
    "RGB-221": {
        "channels": [
            1,
            2
        ],
        "expression": "ch2, ch2, ch1",
        "corrected": true
    },
    "RGB-221-EQU": {
        "channels": [
            1,
            2
        ],
        "expression": "ch2, ch2, ch1",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    },
    "RGB-321": {
        "channels": [
            1,
            2,
            3
        ],
        "expression": "ch3, ch2, ch1",
        "corrected": true
    },
    "RGB-321-EQU": {
        "channels": [
            1,
            2,
            3
        ],
        "expression": "ch3, ch2, ch1",
        "equalize": true,
        "normalize": true,
        "corrected": true
    },
    "RGB-321-CONT": {
        "channels": [
            1,
            2,
            3
        ],
        "expression": "ch3 * 1.8 - 0.25, ch2 * 1.8 - 0.25, ch1 * 1.8 - 0.25",
        "corrected": true
    },
    "4-EQU": {
        "channels": [
            4
        ],
        "expression": "1 - ch4",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    },
    "5-EQU": {
        "channels": [
            5
        ],
        "expression": "1 - ch5",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    }
}