{
    "RGB-221": {
        "expression": "ch2, ch2, ch1",
        "corrected": true
    },
    "RGB-221-EQU": {
        "expression": "ch2, ch2, ch1",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    },
    "RGB-321": {
        "expression": "ch3, ch2, ch1",
        "corrected": true
    },
    "RGB-321-EQU": {
        "expression": "ch3, ch2, ch1",
        "equalize": true,
        "normalize": true,
        "corrected": true
    },
    "RGB-(23)21": {
        "expression": "(ch3 * 0.4 + ch2 * 0.6) * 2.2 - 0.15, ch2 * 2.2 - 0.15, ch1 * 2.2 - 0.15",
        "corrected": true
    },
    "4-EQU": {
        "expression": "ch4",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    }
}