{
    "RGB-221": {
        "expression": "ch2, ch2, ch1",
        "corrected": true
    },
    "RGB-221-EQU": {
        "expression": "ch2, ch2, ch1",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    },
    "RGB-(4)221": {
        "expression": "ch1 < 0.065 ? (ch4 - 0.6) * 2.66 : ch2 * 2.2 - 0.15, ch1 < 0.065 ? (ch4 - 0.6) * 2.66 : ch2 * 2.2 - 0.15, ch1 < 0.065 ? (ch4 - 0.6) * 2.66 : ch1 * 2.2 - 0.15",
        "corrected": true
    },
    "4-EQU": {
        "expression": "ch4",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    },
    "RGB-124": {
        "expression": "ch1, ch2, ch4",
        "corrected": true
    },
    "RGB-124-EQU": {
        "expression": "ch1, ch2, ch4",
        "equalize": true,
        "normalize": true,
        "corrected": true,
        "projected": true
    }
}